edited file

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,8 +1,14 @@
 #!/bin/bash
-PYFILE=$PYFILE
-if
-[ -f "$PYFILE" ]; then
-/usr/bin/python3 "$PYFILE"
-else
-echo "Error: Python file not found!"
+
+# Check if the $PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+echo "Error: \$PYFILE environment variable is not set."
+exit 1
 fi
+# Check if the specified Python file exists
+if [ ! -f "$PYFILE" ]; then
+echo "Error: Python file '$PYFILE' not found."
+exit 1
+fi
+# Run the Python script
+python3 "$PYFILE"
